############################################################
# ライブラリ
############################################################
[[plugins]]
repo      = 'Shougo/vimproc'
lazy      = 0

[[plugins]]
repo      = 'xolox/vim-misc'
lazy      = 0

[[plugins]]
repo      = 'xolox/vim-shell'
lazy      = 0

[[plugins]]
repo      = 'Shougo/tabpagebuffer.vim'
lazy      = 1
on_path   = '.*'

[[plugins]]
repo      = 'osyo-manga/shabadou.vim'
lazy      = 1

[[plugins]]
repo      = 'kana/vim-submode'
lazy      = 1
on_map    = ['gh', 'gw', ',w']


############################################################
# 表示
############################################################
[[plugins]]
repo      = 'YoshihiroIto/molokai'
lazy      = 0

[[plugins]]
repo      = 'itchyny/lightline.vim'
lazy      = 0

[[plugins]]
repo      = 'LeafCage/foldCC.vim'
lazy      = 1
on_ft     = ['vim', 'xml']

[[plugins]]
repo      = 'YoshihiroIto/syntastic'
lazy      = 1
on_ft     = ['go', 'ruby', 'python']


############################################################
# 検索
############################################################
[[plugins]]
repo      = 'YoshihiroIto/vim-jumpbrace'
lazy      = 1
on_map    = '<Plug>'

[[plugins]]
repo      = 'osyo-manga/vim-anzu'
lazy      = 1
on_map    = '<Plug>'

[[plugins]]
repo      = 'haya14busa/vim-asterisk'
lazy      = 1
on_map    = '<Plug>'

[[plugins]]
repo      = 'vim-scripts/matchit.zip'
lazy      = 1
on_path   = '.*'

[[plugins]]
repo      = 'haya14busa/incsearch.vim'
lazy      = 1
on_cmd    = 'IncSearchNoreMap'
on_map    = '<Plug>'

[[plugins]]
repo      = 'rhysd/clever-f.vim'
lazy      = 1
on_map    = '<Plug>'

[[plugins]]
repo      = 'easymotion/vim-easymotion'
lazy      = 1
on_map    = '<Plug>(easymotion'


############################################################
# 補完
############################################################
[[plugins]]
repo      = 'Shougo/neocomplete.vim'
lazy      = 1
on_i      = 1

[[plugins]]
repo      = 'Shougo/neoinclude.vim'
lazy      = 1
depends   = 'neocomplete.vim'
on_i      = 1

[[plugins]]
repo      = 'Shougo/neosnippet.vim'
lazy      = 1
depends   = 'neocomplete.vim'
on_i      = 1


############################################################
# 編集
############################################################
[[plugins]]
repo      = 'tomtom/tcomment_vim'
lazy      = 1
on_func   = 'tcomment'
on_map    = 'gc'
on_cmd    = 'TComment'

[[plugins]]
repo      = 'osyo-manga/vim-over'
lazy      = 1
on_cmd    = 'OverCommandLine'

[[plugins]]
repo      = 'LeafCage/yankround.vim'
lazy      = 1
on_map    = '<Plug>'

[[plugins]]
repo      = 'nishigori/increment-activator'
lazy      = 1
on_map    = ['<C-x>', '<C-a>']

[[plugins]]
repo      = 'junegunn/vim-easy-align'
lazy      = 1
on_map    = '<Plug>(EasyAlign)'

[[plugins]]
repo      = 'thinca/vim-qfreplace'
lazy      = 1
on_ft     = ['unite', 'quickfix']

[[plugins]]
repo      = 'tpope/vim-endwise'
lazy      = 1
on_ft     = ['vim', 'ruby', 'lua']

[[plugins]]
repo      = 'kana/vim-smartinput'
lazy      = 1
on_i      = 1


############################################################
# ファイル
############################################################
[[plugins]]
repo      = 'kana/vim-altr'
lazy      = 1
on_map    = '<Plug>'

[[plugins]]
repo      = 'YoshihiroIto/vim-auto-mirroring'
lazy      = 1
on_path   = '.*'


############################################################
# アプリ
############################################################
[[plugins]]
repo      = 'YoshihiroIto/vim-icondrag'
lazy      = 1
on_path   = '.*'

[[plugins]]
repo      = 'beckorz/previm'
lazy      = 1
depends   = 'open-browser.vim'
on_ft     = 'markdown'

[[plugins]]
repo      = 'tyru/open-browser.vim'
lazy      = 1
on_func   = 'openbrowser'
on_cmd    = 'OpenBrowser'

[[plugins]]
repo      = 'Shougo/vimfiler.vim'
lazy      = 1
depends   = 'unite.vim'
on_map    = '<Plug>'
on_path   = '.*'

[[plugins]]
repo      = 'rhysd/wandbox-vim'
lazy      = 1

[[plugins]]
repo      = 'Shougo/vimshell.vim'
lazy      = 1
on_cmd    = 'VimShellPop'

[[plugins]]
repo      = 'glidenote/memolist.vim'
lazy      = 1
depends   = 'unite.vim'
on_cmd    = ['MemoNew', 'MemoList', 'MemoGrep']

[[plugins]]
repo      = 'thinca/vim-quickrun'
lazy      = 1
depends   = ['shabadou.vim', 'wandbox-vim']
on_map    = '<Plug>'


############################################################
# Unite
############################################################
[[plugins]]
repo      = 'Shougo/unite.vim'
lazy      = 1
depends   = 'neomru.vim'
on_cmd    = ['Unite', 'UniteResume', 'UniteWithCursorWord']

[[plugins]]
repo      = 'Shougo/neomru.vim'
lazy      = 1
on_path   = '.*'

[[plugins]]
repo      = 'Shougo/unite-outline'
lazy      = 1
on_source = 'unite.vim'

[[plugins]]
repo      = 'osyo-manga/unite-quickfix'
lazy      = 1
on_source = 'unite.vim'

[[plugins]]
repo      = 'YoshihiroIto/vim-unite-giti'
lazy      = 1
on_source = 'unite.vim'
on_cmd    = 'GitiFetch'

[[plugins]]
repo      = 'tsukkee/unite-tag'
lazy      = 1
on_source = 'unite.vim'

[[plugins]]
repo      = 'sgur/unite-everything'
lazy      = 1
on_source = 'unite.vim'


############################################################
# C#
############################################################
[[plugins]]
repo      = 'OmniSharp/omnisharp-vim'
lazy      = 1
on_ft     = 'cs'


############################################################
# C++
############################################################
[[plugins]]
repo      = 'Mizuchi/STL-Syntax'
lazy      = 1
on_ft     = 'cpp'

[[plugins]]
repo      = 'vim-jp/vim-cpp'
lazy      = 1
on_ft     = 'cpp'

[[plugins]]
repo      = 'rhysd/vim-clang-format'
lazy      = 1
on_cmd    = 'ClangFormat'


############################################################
# Go
############################################################
[[plugins]]
repo      = 'google/vim-ft-go'
lazy      = 1
on_ft     = 'go'

[[plugins]]
repo      = 'vim-jp/vim-go-extra'
lazy      = 1
on_ft     = 'go'

[[plugins]]
repo      = 'nsf/gocode'
lazy      = 1
on_ft     = 'go'

[[plugins]]
repo      = 'dgryski/vim-godef'
lazy      = 1
on_ft     = 'go'


############################################################
# Xml
############################################################
[[plugins]]
repo      = 'YoshihiroIto/vim-closetag'
lazy      = 1
on_func   = 'closetag'


############################################################
# TypeScript
############################################################
[[plugins]]
repo      = 'clausreinke/typescript-tools.vim'
lazy      = 1
on_ft     = 'typescript'


############################################################
# Git
############################################################
[[plugins]]
repo      = 'tpope/vim-fugitive'
lazy      = 0

[[plugins]]
repo      = 'airblade/vim-gitgutter'
lazy      = 1
on_func   = 'gitgutter'
on_cmd    = ['GitGutter', 'GitGutterNextHunk', 'GitGutterPrevHunk']

[[plugins]]
repo      = 'cohama/agit.vim'
lazy      = 1
on_cmd    = ['Agit', 'AgitFile']


############################################################
# ファイルタイプ
############################################################
[[plugins]]
repo      = 'itchyny/vim-autoft'
lazy      = 0

[[plugins]]
repo      = 'beyondmarc/hlsl.vim'
lazy      = 1
on_ft     = 'hlsl'

[[plugins]]
repo      = 'cespare/vim-toml'
lazy      = 1
on_ft     = ['toml', 'markdown']

[[plugins]]
repo      = 'jelera/vim-javascript-syntax'
lazy      = 1
on_ft     = 'javascript'

[[plugins]]
repo      = 'stephpy/vim-yaml'
lazy      = 1
on_ft     = 'yaml'

[[plugins]]
repo      = 'tikhomirov/vim-glsl'
lazy      = 1
on_ft     = 'glsl'

[[plugins]]
repo      = 'tpope/vim-markdown'
lazy      = 1
on_ft     = 'markdown'

[[plugins]]
repo      = 'vim-ruby/vim-ruby'
lazy      = 1
on_ft     = 'ruby'

[[plugins]]
repo      = 'vim-scripts/JSON.vim'
lazy      = 1
on_ft     = ['json', 'markdown']

[[plugins]]
repo      = 'leafgarland/typescript-vim'
lazy      = 1
on_ft     = 'typescript'


############################################################
# テキストオブジェクト
############################################################
# https://github.com/kana/vim-textobj-user/wiki
# http://d.hatena.ne.jp/osyo-manga/20130717/1374069987
[[plugins]]
repo      = 'kana/vim-textobj-user'
lazy      = 1

# #
[[plugins]]
repo      = 'anyakichi/vim-textobj-ifdef'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'a#'], ['xo', 'i#']]

# c
[[plugins]]
repo      = 'glts/vim-textobj-comment'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'ac'], ['xo', 'ic']]

# .
[[plugins]]
repo      = 'rhysd/textobj-wiw'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', '<Plug>']]

# e
[[plugins]]
repo      = 'kana/vim-textobj-entire'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'ae'], ['xo', 'ie']]

# i I
[[plugins]]
repo      = 'kana/vim-textobj-indent'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'ai'], ['xo', 'aI'], ['xo', 'ii'], ['xo', 'iI'], ['xo', '<Plug>(textobj-indent']]

# l
[[plugins]]
repo      = 'kana/vim-textobj-line'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'al'], ['xo', 'il']]

# b
[[plugins]]
repo      = 'rhysd/vim-textobj-anyblock'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'ab'], ['xo', 'ib']]

# v V
[[plugins]]
repo      = 'rhysd/vim-textobj-word-column'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'av'], ['xo', 'aV'], ['xo', 'iv'], ['xo', 'iV']]

# a
[[plugins]]
repo      = 'sgur/vim-textobj-parameter'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', '<Plug>']]

# f{char}
[[plugins]]
repo      = 'thinca/vim-textobj-between'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'af'], ['xo', 'if']]

# x
[[plugins]]
repo      = 'whatyouhide/vim-textobj-xmlattr'
lazy      = 1
depends   = 'vim-textobj-user'
on_map    = [['xo', 'ax'], ['xo', 'ix']]


############################################################
# オペレータ
############################################################
# http://qiita.com/rbtnn/items/a47ed6684f1f0bc52906
[[plugins]]
repo      = 'kana/vim-operator-user'
lazy      = 1

# t
[[plugins]]
repo      = 'YoshihiroIto/vim-operator-tcomment'
lazy      = 1
depends   = ['vim-operator-user', 'tcomment_vim']
on_map    = [['nx', '<Plug>']]

# <Leader>r
[[plugins]]
repo      = 'deris/vim-rengbang'
lazy      = 1
depends   = 'vim-operator-user'
on_map    = [['nx', '<Plug>(operator-rengbang']]
on_cmd    = 'RengBang'

# R
[[plugins]]
repo      = 'kana/vim-operator-replace'
lazy      = 1
depends   = 'vim-operator-user'
on_map    = [['nx', '<Plug>']]

# S
[[plugins]]
repo      = 'rhysd/vim-operator-surround'
lazy      = 1
depends   = 'vim-operator-user'
on_map    = [['nx', '<Plug>']]

# _
[[plugins]]
repo      = 'tyru/operator-camelize.vim'
lazy      = 1
depends   = 'vim-operator-user'
on_map    = [['nx', '<Plug>']]

# <Leader>j
[[plugins]]
repo      = 'osyo-manga/vim-operator-jump_side'
lazy      = 1
depends   = 'vim-operator-user'
on_map    = [['nx', '<Plug>(operator-jump']]

